# Generated by Django 4.1.1 on 2022-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название парика')),
                ('img', models.ImageField(blank=True, default='no_image.jpg', upload_to='')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField()),
                ('group', models.CharField(choices=[('artificial wig', 'artificial wig'), ('mixed wig', 'mixed wig'), ('natural wig', 'natural wig'), ('accessories', 'accessories')], default='natural wig', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
